language: go
go:
- tip
before_install:
- openssl aes-256-cbc -K $encrypted_04152ea6dd71_key -iv $encrypted_04152ea6dd71_iv
  -in deploy.json.enc -out deploy.json -d

deploy:
  provider: gae
  keyfile: deploy.json
  default: true
  project: echo-1102